export const INPUT = 'Input';
export const DROPDOWN = 'Dropdown';
export const MULTIPLE_QUESTION = 'Multiple_selection';
export const SINGLE_QUESTION = 'Single_selection';
export const SUB_QUESTION = 'Sub_question';

export const arrayData = [
  {
    Q_type: 'Input',
    Q_id: '1',
    Section: 'General',
    Q_no: '1',
    Dropdownkeys: '',
    RadioButtons: "",
    Q_Main_category: 'Safai',
    Q_question: 'What is your name',
  },
  {
    Q_type: 'Dropdown',
    Q_id: '2',
    Section: 'Family',
    Q_no: '2',
    Dropdownkeys: [
      {label: 20, value: 20},
      {label: 21, value: 21},
      {label: 22, value: 22},
      {label: 23, value: 23},
    ],
    RadioButtons: "",
    Q_Main_category: 'Identified',
    Q_question: 'What is your Age?',
  },
  {
    Q_type: 'Multiple_selection',
    Q_id: '3',
    Section: 'Others',
    Q_no: '3',
    Dropdownkeys: '',
    RadioButtons: "",
    Q_Main_category: 'identified',
    Q_question: 'What is your dob?',
  },
  {
    Q_type: 'Single_selection',
    Q_id: '4',
    Section: 'Family',
    Q_no: '4',
    Dropdownkeys: '',
    RadioButtons: ['male', 'female', 'others'],
    Q_Main_category: 'Ms death',
    Q_question: 'What is your Gender?',
  },
  {
    Q_type: 'Sub_question',
    Q_id: '5',
    Section: 'General',
    Q_no: '5',
    Dropdownkeys: '',
    Q_Main_category: 'Safai',
    Q_question: 'What is your Name?',
  },
  {
    Q_type: 'Input',
    Q_id: '6',
    Section: 'Family',
    Q_no: '6',
    Q_Main_category: 'Identified',
    Q_question: 'What is your Age?',
  },
  {
    Q_type: 'Dropdown',
    Q_id: '7',
    Section: 'Others',
    Q_no: '7',
    Dropdownkeys: [
      {label: 2000, value: 2000},
      {label: 2001, value: 2001},
      {label: 2002, value: 2002},
      {label: 2003, value: 2003},
    ],
    Q_Main_category: 'Ms Death',
    Q_question: 'What is your dob?',
  },
  {
    Q_type: 'Multiple_selection',
    Q_id: '8',
    Section: 'General',
    Q_no: '8',
    Dropdownkeys: '',
    Q_Main_category: 'Safai',
    Q_question: 'What is your Gender?',
  },
  {
    Q_type: 'Single_selection',
    Q_id: '9',
    Section: 'Family',
    Q_no: '9',
    Dropdownkeys: '',
    Q_Main_category: 'Identified',
    Q_question: 'What is your Name?',
  },
  {
    Q_type: 'Sub_question',
    Q_id: '10',
    Section: 'Others',
    Q_no: '10',
    Dropdownkeys: '',
    Q_Main_category: 'Ms Death',
    Q_question: 'What is your Age?',
  },
];
